blog/urls.py
from django.urls import path


from . import views

app_name = "blog"

urlpatterns = [
	path('', views.listar_noticias, name="listar_noticias"),
	path('<int:id_noticia>/', views.ver_noticia,name="ver_noticia")
]

blog/models.py
from django.db import models

class Noticia(models.Model):
	titulo = models.CharField(max_length=200)
	descripcion = models.CharField(max_length=1000)
	fecha_pub = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return "%s %s" % (self.titulo,self.fecha_pub)

blog/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse

#MVT
#MODEL
#VIEW
#TEMPLATE
#Importacion de librerias personales 
from . import models


def listar_noticias(resquest):
	"""
		obtiene las noticias de la base de datos

		Retorna:
			El listado de las noticias
	"""
	#obtiene el listado de todas las noticias
	#De la base de datos y la asigna a la variable
	#noticias
	noticias = models.Noticia.objects.all()
	
	#Retorna todo renderizado para ser leido en el
	#explorador, tiene tres parametros
	#solicitud(resquest), plantilla de datos y datos
	return render(
					resquest, 
					'./noticias/index.html', 
					{'news':noticias}
				)

def ver_noticia(resquest, id_noticia):
	"""
		obtiene una noticia de la base de datos

		parametros:
			id noticia es numerico y hace referencia
			al identificador de la noticia buscada

		retorna:
			la noticia buscada si existe
	"""

	noticia = models.Noticia.objects.get(id=id_noticia)

	return render(
					resquest,
					'./noticias/detalle.html',
					{'noticia':noticia}
				)

blog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>
		{% block titulo %}noticia{% endblock %}
	</title>

		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
	<head>
	<body class="bg-danger">
		<div id="header" class=" bg-body">
			<!--
				h1 {h = header} es igual a encabezado uno
				display mostrar - tamaño
			-->
			<a href="{% url 'blog:listar_noticias' %}" class=
			"text-secondary">
				<h1 class="display-3 text-center text-secondary">
					Nahum <b><i>news</i></b></h1>
				</a>
			</p>
		</div>

		<div class="container bg-white" id="principal">
			{% block informacion %}

			{% endblock %}
		</div>
	</body>
	</html>

blog/templates/noticias/detalle.html
<!-- extiende la configuracion y maquetacion de la pagina base-->
{% extends 'base.html' %}


{% block titulo %}
	{{ noticia.titulo }}
{% endblock %}


<!--
	para la informacion que va a ser mostrada en el bloque
	informacion de la pagina base.html
-->
 {% block informacion %}

 	<h1>{{ noticia.titulo }}</h1>

 	<p>{{noticia.descripcion}}</p>
 	<div class="text-secondary">
 		fecha de publicion: {{noticia.fecha_pub }}
 	</div>
 {% endblock %}

blog/templates/noticias/index.html
<!-- extiende la configuracion y maquetacion de la pagina base-->
{% extends 'base.html' %}

<!--
	para la informacion que va a ser mostrada en el bloque
	informacion de la pagina base.html
-->
 {% block informacion %}
	{% for new in news %}
		<div class="p-1">
			<h2>{{ new.titulo }}</h2>
			<hr>
			<p>{{ new.descripcion }}</p>
			<a href="{% url 'blog:ver_noticia' new.id %}">
				<button class="btn btn-primary">ver paps</button>
			</a>

		</div>
	{% endfor %}
{% endblock %}